language: go
install:
    - go get github.com/shopify/sarama
    - go get github.com/satori/go.uuid
    - go get github.com/justsocialapps/assert
    - go get github.com/justsocialapps/justlib
    - go get github.com/alecthomas/gometalinter
script:
    - gometalinter --install
    - gometalinter .
    - go test ./...
